from . import hr_employee
from . import metric_compute
from . import social_connectors
from . import project_task
from . import meeting_attendance  
from . import calendar_event    
from . import intern_evaluation
from . import hr_kpi_dashboard
from . import intern_voucher
from . import weekly_winner_history
