{
    'name': 'FAMTECH Intern Dashboard',
    'version': '1.0',
    'depends': [
        'hr',
        'hr_attendance',
        'hr_holidays', 
        # 'approval',          - for enterprise only
        'hr_expense',
        'project',
        'mail',
        'website',
        'calendar',
        'portal'
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/meeting_attendance_views.xml',
        'views/calendar_event_views.xml',
        'views/intern_dashboard_views.xml',
        'views/hr_employee_view.xml',
        'views/project_task_view.xml',
        'views/crm_lead_view.xml',
        'views/intern_evaluation_views.xml',
        'views/intern_contract_hours_views.xml',
        'views/hr_kpi_dashboard_views.xml',
        'views/hr_kpi_dashboard_report.xml',
        'data/mail_template_intern_hours.xml', 
        'data/mail_template_performance_alert.xml',
        'data/mail_template_approaching_hours.xml',
        'data/cron_intern_hours_alert.xml',
        'data/cron_compute_intern_metrics.xml',
        'data/cron_daily_intern_score_snapshot.xml',
        'views/portal_intern_onboarding.xml',
        'views/website/intern_dashboard.xml',
        'views/website/intern_navbar.xml',
        'views/website/intern_onboarding.xml',
        'views/website/intern_rewards.xml',
        'views/website/intern_error.xml',
        # 'views/res_config_settings_views.xml',
        # 'data/gamification_badges.xml',     
    ],
    'assets': {
        'web.assets_backend': [
            'famtech_intern_dashboard/static/src/js/timeliness_responsiveness_scatter.js',
            'famtech_intern_dashboard/static/src/xml/timeliness_responsiveness_scatter.xml',
            'famtech_intern_dashboard/static/src/js/contract_vs_rendered_hours_chart.js',
            'famtech_intern_dashboard/static/src/xml/contract_vs_rendered_hours_chart.xml',
            'famtech_intern_dashboard/static/src/xml/graph_measure_override.xml',
            'famtech_intern_dashboard/static/src/scss/intern_evaluation_list.scss',
        ],
        'web.assets_website': [
            'famtech_intern_dashboard/static/src/website/css/global.css',
            'famtech_intern_dashboard/static/src/website/css/onboarding.css',
            'famtech_intern_dashboard/static/src/website/css/dashboard.css',
        ],
    },
    'installable': True,
}
